rango/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^category/(?P<category_id>[0-9]+)/$', views.detail, name='detail2'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
    url(r'^category/(?P<category_id>[0-9]+)/like/$', views.like, name='like'),
    url(r'^category/views/(?P<category_id>[0-9]+)/$', views.increaseView, name='increaseView'),
    url(r'category/likes/(?P<category_id>[0-9]+)/$', views.increaseLike, name='increaseLike'),
    url(r'category/(?P<category_id>[0-9]+)/views/$', views.increaseDetailView, name='increaseDetailView'),
    url(r'category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add/$', views.add_page, name='add_page'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    url(r'logout/$', views.user_logout, name='logout'),
]

tango_with_django/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^rango/', include('rango.urls', namespace='rango')),
    url(r'^admin/', include(admin.site.urls)),
]

rango/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    # override the save() method of Category to update slug field
    # everythime the category name changes, the slug will also change.
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title


class UserProfile(models.Model):
    # links UserProfile to a User model instance
    user = models.OneToOneField(User)

    # additional attributes to include
    website = models.URLField(blank=True) # blank=True means they are allowed to be blank if ncessary
    picture = models.ImageField(upload_to='profile_images', blank=True) #upload_to folder will be joined with MEDIA ROOT

    # override __unicode__ method to return something meaningful
    def __unicode__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Category, Page, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Enter category name here")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # an inline class to provide additional information on the form
    class Meta:
        #provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Enter title of page")
    url = forms.URLField(max_length=200,  help_text="Enter URL of page")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        fields = ('title', 'url', 'views', )

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        #If url is not empty and doesn't start with http://, prepend http://
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from datetime import datetime
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http.response import HttpResponseRedirect, HttpResponse
from .models import Category, Page
from .forms import CategoryForm, PageForm, UserProfileForm, UserForm


def index(request):
    # category_list = Category.objects.order_by('-likes')[:5]
    # page_list = Page.objects.order_by('-views')[:5]

    category_list = Category.objects.order_by('-likes')[:5]

    # set up test cookie;
    request.session.set_test_cookie()

    # setting up session to track number of visits of a visitor
    visits = request.session.get('visits')
    # If visits doesn't exist/ if the user hasn't visited
    if not visits:
        visits = 1

    reset_last_visit_time = False

    last_visit = request.session.get('last_visit')

    if last_visit:
        last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")

        if (datetime.now() - last_visit_time).seconds > 0:
            # reassign the value of the coolike to +1 of what it was before.
            visits += 1
            # update the last visit cookie too.
            reset_last_visit_time = True
    else:
    # cookie last visit doesn't exist, so create it to the current date/time
        reset_last_visit_time = True

    if reset_last_visit_time:
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = visits

    return render(request, 'rango/index.html', {'category_list':category_list, 'visits':visits})
    # return render_to_response('rango/index.html', {'category_list':category_list})


def about(request):
    # get the value of visits from request.session
    visits = request.session.get('visits')
    # if there is no value in visits/ False
    if not visits:
        # declare and initialize visits = 1
        visits = 1

    # get the value (time) of the last_visit from request.session (the time visitor last visited the page)
    last_visit = request.session.get('last_visit')
    # set up a flag Boolean variable to determine if we need to update last_visit time
    update_last_visit_time = False

    # if there's a last_visit/ visitor visited the page
    if last_visit:
        # get the datetime when the visitor visited the page
        last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")
        # get the time difference between now and the last visit, and test to see if the difference is greater than 0;
        # we can change 0 to 5 minutes or 24 hours if we need to
        if (datetime.now() - last_visit_time).seconds > 0:
            # update the visit time
            visits += 1
            # change the flag to say we need to update the last visit time
            update_last_visit_time = True
    # the visitor hasn't visited the page yet, we'll set up their first visit by setting up the 'last_visit' value in the next step.
    else:
        # if they haven't visited yet, we'll take it as we need to update their last visit time
        update_last_visit_time = True

    # if we need to reset/update last visit time
    if update_last_visit_time:
        # update both last_visit/ visits in the request.session dictionary
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = visits

    return render(request, 'rango/about.html', {'about' : "Rango says this is the about page", 'visits': visits})
    # return render_to_response('rango/about.html', {'about': "Rango says this is AbOuT Page"})


def detail(request, category_id):
    cat = get_object_or_404(Category, pk=category_id)
    return render(request, 'rango/detail.html', {'category':cat})
    # return render_to_response('rango/detail.html', {'category':cat})


def category(request, category_name_slug):
    cat = Category.objects.get(slug = category_name_slug)

    try:
        pages = Page.objects.filter(category=cat)

    except (KeyError, Page.DoesNotExist):
        pass
    return render(request, 'rango/category.html', {'category_name': cat.name, 'pages':pages, 'category': cat})
    # return render_to_response('rango/category.html', {'category_name':cat.name, 'pages': pages, 'category':cat })


def like(request, category_id):
    cat = get_object_or_404(Category, pk=category_id)
    cat.likes += 1
    cat.save()

    return HttpResponseRedirect(reverse('rango:detail2', args=(cat.id,)))
    # return HttpResponseRedirect('/rango/')


@login_required
def increaseView(request, category_id):
    try:
        cate = Category.objects.get(pk = request.POST['category'])
    except (KeyError, Category.DoesNotExist):
        return index(request)
    else:
        cate.views += 10
        cate.save()
    return HttpResponseRedirect('/rango/')


@login_required
def increaseLike(request, category_id):
    categ = get_object_or_404(Category, pk=category_id)

    try:
        likeNumber = request.POST['likes']
    except (KeyError):
        return index(request)
    else:
        likeNumber = int(likeNumber)
        if likeNumber <= 0:
            likeNumber = 0
        else:
            categ.likes += likeNumber
            categ.save()
    return HttpResponseRedirect('/rango/')


@login_required
def increaseDetailView(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    try:
        page = category.page_set.get(pk = request.POST['views'])
    except (KeyError, Page.DoesNotExist):
        return render(request,'rango/detail.html',{'category':category, 'error_message': "Sorry, you didn't select a views."})
    else:
        page.views += 5
        page.save()
    return HttpResponseRedirect(reverse('rango:category', args=(category.id,)))


@login_required
def add_category(request):

    # test to see if the user is logged in using the user object provided by the request context
    if not request.user.is_authenticated():
        return HttpResponse('You are not logged in.')
    else:
        # A Http POST?
        if request.method == 'POST':
            form = CategoryForm(request.POST)
            # Have form been provided with a valid form?
            if form.is_valid():
                #Save the new category to the database
                form.save(commit=True)

                #Now call the index() view.
                return index(request)

            else:
                #The supplied form contained errors, print them to the terminal
                print form.errors

        else:
            #if the method is not POST, display the form to enter details
            form = CategoryForm()

        return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        cat  = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        cat = None

    #check if it's a post
    if request.method == 'POST':
        form = PageForm(request.POST)
        # have form been provided with a valid form?
        if form.is_valid():
            # save the new page to the db
            if cat:
                page = form.save(commit=False)
                page.category = cat
                page.views = 0
                page.save()

            # return detail(request, cat.id)
            return HttpResponseRedirect(reverse('rango:detail2', args=(cat.id, )))
        else:
            print form.errors

    else:
        # if method is not POST, display the form to enter details
        form = PageForm()

    return render(request, 'rango/add_page.html',  {'form':form, 'category':cat})


def register(request):

    if request.session.test_cookie_worked():
        print ">>> TEST COOKIE WORKED!"

    # A boolean value for telling the template if registration successful.
    # Set to False initially. Code changes value to True if registration successful.
    registered = False

    # if it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        # If the two forms are valid..
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to db
            user = user_form.save()

            # Now we hash the password with the set_password method
            # Once hashed, we can update the user object
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance
            # Since we need to set the user attribute ourselves, we set to commit = False
            # This delays saving the model until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user # associate the user with user profile info

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now save the UserProfile instance
            profile.save()

            registered = True # update the registered variable to tell the template registration was successful.

            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            # They will also be shown to the user
        else:
            print  user_form.errors, profile_form.errors

    # Not a Http POST, so we render our form using the two ModelForm instances.
    # These forms will be blank, ready for user input
    else:
        user_form = UserForm()

rango/templates/rango/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <h2>Rango's About</h2>
    {{ about }} <br />
    <img src="{% static 'images/rango.jpg' %}" alt="Image of Rango"/><br />
    <h3>Hello, you have visited our page {{ visits }} time{{ visits| pluralize }}</h3>
    <a href="{%  url 'rango:index' %}">Back Home</a>
{% endblock %}

{% block footer %}
    <p>Rango About Footer</p>
{% endblock %}

rango/templates/rango/add_category.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <h2>Rango's Add Category Page</h2>

    <form action="{% url 'rango:add_category'  %}" method="post">
        {% csrf_token %}
        {%  for hidden in form.hidden_fields %}
            Hidden Fields - - {{ hidden }}<br />
        {% endfor %}

        {% for field in form.visible_fields %}
           Error: {{ field.errors }} <br />
           Help Text:  {{ field.help_text }} <br />
           Field: {{ field }} <br />
        {% endfor %}
        <input type="submit" name="submit" value="Add Category"/>
    </form>


{% endblock content %}

rango/templates/rango/add_page.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <h2>Rango's Add Page</h2>
    <hr />
    <form action="{% url 'rango:add_page' category.slug %}" method="post">
         {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Add Page"/>
    </form>

{% endblock content %}

rango/templates/rango/category.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} {{ category_name }} {%  endblock %}
{% block content %}
    <h2>Rango's Category Page</h2>
    <h3>Category: {{ category_name }}</h3><hr />
    {% if category %}
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li>Category: {{ page.category }} - Title: <a href="{{ page.url }}">{{ page.title }}</a> - Views: {{ page.views }}</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Sorry, no page to show.</p>
        {% endif %}
        {%  if user.is_authenticated %}
            <h2><a href="{% url 'rango:add_page' category.slug %}">Add New Page in Category {{ category.name }}</a></h2>
        {% endif %}
    {% else %}
        <p>Sorry, the category {{ category_name }} does not exist</p>
    {% endif %}

    <img src="{% static 'images/rango3.jpg' %}" alt="Rango 2 image"/> <br />
    <a href="{% url 'rango:index' %}">Go Home</a>
{% endblock content %}

rango/templates/rango/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Detail {% endblock %}
{% block content %}
    <h2>Rango's Details</h2>
    {% if error_message %}
        {{ error_message }}
    {% endif %}
    {% if category %}
        <ul>
        {% for page in category.page_set.all %}
            <li>Category - {{ page.category }} - Title - <a href="{{ page.url }}">{{ page.title }}</a> - Views - {{ page.views }}</li>
        {% endfor %}
        </ul>
        <br /> <hr />
        {% if user.is_authenticated %}
            {% for pag in category.page_set.all %}
                <form method="post" action="{% url 'rango:increaseDetailView' category.id %}">
                    {% csrf_token %}
                    <input type="radio" name="views" value="{{ pag.id }}"/>
                    <label>{{ pag.title }}</label>
                    <input type="submit" value="Views + 5" />
                </form>
            {% endfor %}
        {% else %}
            <p>Log in to Rango to add View Rango</p>
        {% endif %}
    {% else %}
        <p>Sorry, no category to show.</p>
    {% endif %}
    <img src="{% static 'images/rango2.jpg' %}" alt="Rango 2 image"/> <br />
    <a href="{% url 'rango:index' %}">Go Home</a>
{% endblock content %}

rango/templates/rango/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <h2>Rango's Home</h2>
    {%  if user.is_authenticated %}
        <h3>Rango says hello {{ user.username }}. Welcome abord.</h3>
        <h3><a href="{% url 'rango:restricted' %}">Go to Restricted View</a></h3>
        <h2><a href="{% url 'rango:add_category' %}">Add a Category</a></h2>
        <h3><a href="{% url 'rango:logout' %}">Log Out</a></h3>
    {% else %}
        <h3>Rango says hello there, please login</h3>
        <h3><a href="{% url 'rango:register' %}">Registered with Rango</a></h3>
        <h3><a href="{% url 'rango:login' %}">Login to Rango</a></h3>
    {% endif %}

    {% if category_list %}
        <ul>
        {% for category in category_list %}
            <li>Name:<a href="{% url 'rango:detail2' category.id %}">{{ category.name }}</a> -- Views: {{ category.views }} -- Likes: {{ category.likes }}</li>
            <li>Name:<a href="{% url 'rango:category' category.slug %}">{{ category.name }}</a> -- Views: {{ category.views }} -- Likes: {{ category.likes }}</li>
        {% endfor %}
        </ul>
        <br /><hr />
        <h2>Top Up Category Likes + 1 </h2>
        {%  if user.is_authenticated %}
            {% for cat in category_list %}
                <form action="{% url 'rango:like' cat.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="likes"/>
                    Total Like: {{ cat.likes }}   Like{{ cat.likes | pluralize }}<input type="submit" name="category" value="Like {{ cat.name }}"/>
                </form>
            {% endfor %}
        {% else %}
            <p>Please log in to Rango first.</p>
        {% endif %}

        <hr />
        <h2>Top Up Category Views + 10 </h2>
        {% if user.is_authenticated %}
            {% for cate in category_list %}
                <form action="{% url 'rango:increaseView' cate.id %}" method="post">
                    {% csrf_token %}
                    Total Views: {{ cate.views }} view{{ cate.views | pluralize }} <input type="hidden" name="category" value="{{ cate.id}}" />
                    <input type="submit" value="Views + 10"/>
                </form>
            {% endfor %}
        {% else %}
            <p>Sorry, please log into Rango first to Like</p>
        {% endif %}
        <br /><hr />

        <h2>Top Up Category Likes by User </h2>
        {% if user.is_authenticated %}
            {% for categ in  category_list %}
                <form method="post" action="{% url 'rango:increaseLike' categ.id %}">
                    {% csrf_token %}
                    <label>Insert How Many Likes You Want to Increase</label>
                    <input type="text" name="likes" value="0"/>
                    <input type="submit" value="Increase Like" />
                </form>
            {% endfor %}
        {% else %}
            <p>Please login to Rango to Like Rango</p>
        {% endif %}
        <br /><hr />

    {% else %}
        <p>Sorry, no category to show.</p>
    {% endif %}
    <img src="{% static 'images/rango.jpg' %}" alt="Rango 2 image"/> <br />
    <h2>Hi, You have visited {{ visits }} times.</h2>
    <a href="{% url 'rango:about' %}">Go About</a>
{% endblock content %}

rango/templates/rango/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Login {% endblock %}
{% block content %}
    <h2>Rango Login</h2>
    {% if error_message %}
        {{ error_message }}
    {% endif %}

    <form method="post" action="{% url 'rango:login' %}">
        {%  csrf_token %}
        <input type="text" name="username" placeholder="{{ username }}" />
        <input type="password" name="password" placeholder="{{ password }}"/>
        <input type="submit" name="submit" value="Login" />
    </form>


{% endblock content %}

rango/templates/rango/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Register {% endblock %}
{% block content %}
    <h2>Rigister with Rango </h2>
    {% if error_message %}
        {{ error_message }}
    {% endif %}
    {% if registered %}
        <p>Rango says: <strong>Thanks</strong>for registering!</p>
        <p><a href="{% url 'rango:index' %}">Go Home</a></p>
    {% else %}
        <p>Register Now</p>
        <form method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
{#            as_p renders each element in a paragraph element#}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="submit" value="Register Rango" />
        </form>
    {% endif %}
    <br />
    <img src="{% static 'images/rango2.jpg' %}" alt="Rango 2 image"/> <br />
{% endblock content %}